
name: CI

on:
  pull_request_target:
    types:
      - synchronize
      - opened
      - reopened

  workflow_dispatch:

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: test basic
        run: |
          pnpm install
          pnpm run test:basic

  advacned:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: advanced-test
        run: |
          pnpm install
          pnpm run test:advanced
